sudo: false
language: php

services:
  - mysql

env:
  global:
    - DB_USER="root"
    - DB_PASS=""

php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - mysql < app/demo.sql
  - composer self-update
  - composer install --dev --no-interaction

script:
  - composer test
