sudo: false
language: php

services:
  - mysql

php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache/files


before_script:
  - composer self-update
  - composer install --dev --no-interaction
  - mysql -u root -e 'create database silex-api;'
  - mysql -u root -p silex-api < app.demo.sql

script:
  - composer test
